/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 thinker.gltf --transform --instance 
Files: thinker.gltf [1.79KB] > C:\3d models\man\the-thinker-by-auguste-rodin\thinker-transformed.glb [146.04KB] (-8059%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/thinker-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rodin_Thinker.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/thinker-transformed.glb')
